[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.34"
optimizer = true
# @review-deploy before production deployment
optimizer_runs = 777
via_ir = true
no_match_contract = "CryticTester"

[invariant]
runs = 3000
depth = 15
fail_on_revert = true

[profile.invariants.invariant]
runs = 3000
depth = 15
fail_on_revert = false

[profile.halmos]
evm_version = "shanghai"
out = "out-halmos"
ast = true

[rpc_endpoints]
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
ethereum_sepolia = "${ETHEREUM_SEPOLIA_RPC_URL}"
optimism_sepolia = "${OPTIMISM_SEPOLIA_RPC_URL}"
avalanche_fuji = "${AVALANCHE_FUJI_RPC_URL}"

[etherscan]
arbitrum_sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 421614 }
base_sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 84532 }
ethereum_sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 11155111 }
optimism_sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 11155420 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
