/*
 * Capacity-error checks are excluded from this spec's use-rule list and run in
 * ChildVault.Capacity.rules.conf with a standalone router that emits the native
 * TokenMaxCapacityExceeded error. The caller fixture captures actual revert
 * bytes without replacing production catch logic or weakening rollback checks.
 *
 * CCIP_005_routerSend_EmitsExactCapacityError
 * CCIP_005_ccipSend_BubblesExactCapacityError
 * CCIP_005_NONCE_005_NONCE_006_REC_002_REC_009_executeEpochWithdraw_RevertWhen_RouterCcipSendCapacityExceeded
 * CCIP_005_REC_001_REC_002_REC_004_REC_009_executeRecovery_REBALANCE_WITHDRAW_Remote_RevertWhen_RouterCcipSendCapacityExceeded
 * CCIP_005_NONCE_005_NONCE_006_REC_002_REC_009_executeRebalance_Remote_RevertWhen_RouterCcipSendCapacityExceeded
 * CCIP_005_REC_001_REC_002_REC_004_REC_009_executeRecovery_EPOCH_WITHDRAW_RevertWhen_RouterCcipSendCapacityExceeded
 */

import "ChildVaultCommon.rules.spec";

using MockCCIPRouter as ccipRouter;

methods {
    function ccipRouter.getFee() external returns (uint256) envfree;
    function ccipRouter.getFeeReverts() external returns (bool) envfree;
    function ccipRouter.ccipSendReverts() external returns (bool) envfree;
    function ccipRouter.capacityError() external returns (bool) envfree;
    function ccipRouter.getLastMessageDataHash() external returns (bytes32) envfree;
}

use rule ADAPTER_003_ADAPTER_005_REBAL_008_REC_006_getTVL_EqualsCcipSendRecovery_WhenNoActiveAdapter;
use rule ADAPTER_003_ADAPTER_005_REBAL_008_REC_006_getTVL_IncludesAdapterTVLAndRecoveries;
use rule REBAL_008_getTVL_RevertWhen_TotalOverflows;
use rule UPGRADE_002_initialize_RevertWhen_AlreadyInitialized;
use rule REENT_001_initialize_RevertWhen_ReentrantCall;
use rule NONCE_001_initialize_Success;
use rule CCIP_001_ccipReceive_RevertWhen_CallerIsNotCCIPRouter;
use rule REENT_001_ccipReceive_RevertWhen_ReentrantCall;
use rule PAUSE_004_ccipReceive_RevertWhen_Paused;
use rule CCIP_001_ccipReceive_RevertWhen_SenderIsNotAllowed;
use rule CCIP_001_ccipReceive_RevertWhen_SenderAndRegisteredVaultAreZero;
use rule CCIP_001_ccipReceive_RevertWhen_SenderEncodingIsMalformed;
use rule NONCE_007_REC_003_ccipReceive_RevertWhen_RecoveryAlreadyPending;
use rule CCIP_002_ccipReceive_RevertWhen_TokenAmountsLengthIsInvalid;
use rule CCIP_002_ccipReceive_RevertWhen_ReceivedTokenIsInvalid;
use rule CCIP_002_ccipReceive_RevertWhen_ReceivedAmountIsZero;
use rule CCIP_003_ccipReceive_RevertWhen_TxDataEncodingIsMalformed;
use rule CCIP_003_ccipReceive_RevertWhen_TxTypeEncodingIsOutOfRange;
use rule CCIP_003_ccipReceive_RevertWhen_TxTypeIsInvalid;
use rule CCIP_001_ccipReceive_EPOCH_NET_DEPOSIT_RevertWhen_SourceChainIsNotParentChain;
use rule CCIP_004_NONCE_003_NONCE_007_ccipReceive_EPOCH_NET_DEPOSIT_RevertWhen_EpochNonceIsNotNew;
use rule NONCE_005_ccipReceive_EPOCH_NET_DEPOSIT_RevertWhen_NoActiveAdapter;
use rule CCIP_003_ccipReceive_EPOCH_NET_DEPOSIT_RevertWhen_PayloadEncodingIsMalformed;
use rule CCIP_003_CCIP_004_NONCE_003_NONCE_004_ccipReceive_EPOCH_NET_DEPOSIT_Success;
use rule NONCE_005_NONCE_006_REC_002_REC_009_ccipReceive_EPOCH_NET_DEPOSIT_FailedDepositStoresRecovery;
use rule CCIP_004_NONCE_003_NONCE_007_ccipReceive_REBALANCE_RevertWhen_RebalanceNonceIsNotNew;
use rule ADAPTER_002_NONCE_005_ccipReceive_REBALANCE_RevertWhen_AdapterNotRegistered;
use rule CCIP_003_ccipReceive_REBALANCE_RevertWhen_PayloadEncodingIsMalformed;
use rule ADAPTER_002_NONCE_005_ccipReceive_REBALANCE_RevertWhen_AdapterVaultIsInvalid;
use rule CCIP_003_CCIP_004_NONCE_003_NONCE_004_ccipReceive_REBALANCE_Success;
use rule NONCE_005_NONCE_006_REC_002_REC_009_ccipReceive_REBALANCE_FailedDepositStoresRecovery;
use rule tryCcipSend_RevertWhen_CallerIsNotSelf;
use rule tryCcipSend_RevertWhen_BridgeAmountIsZero;
use rule tryCcipSend_RevertWhen_DestinationChainIsZero;
use rule tryCcipSend_RevertWhen_DestinationIsSelfChain;
use rule tryCcipSend_RevertWhen_DestinationVaultNotRegistered;
use rule tryCcipSend_RevertWhen_RouterGetFeeReverts;
use rule tryCcipSend_RevertWhen_RouterCcipSendReverts;
use rule tryCcipSend_Success;
use rule PAUSE_004_REC_008_executeRecovery_RevertWhen_Paused;
use rule REENT_001_executeRecovery_RevertWhen_ReentrantCall;
use rule REC_008_executeRecovery_NONE_RevertWhen_NoRecoveryPending;
use rule REC_005_REC_009_executeRecovery_EPOCH_DEPOSIT_RevertWhen_NoActiveAdapter;
use rule REC_005_executeRecovery_EPOCH_DEPOSIT_RevertWhen_DepositFails;
use rule REC_001_REC_004_REC_007_REC_008_executeRecovery_EPOCH_DEPOSIT_Success;
use rule REC_005_REC_009_executeRecovery_REBALANCE_DEPOSIT_RevertWhen_NoActiveAdapter;
use rule REC_005_executeRecovery_REBALANCE_DEPOSIT_RevertWhen_DepositFails;
use rule REC_001_REC_004_REC_007_REC_008_executeRecovery_REBALANCE_DEPOSIT_Success;
use rule REC_003_ccipSend_RevertWhen_RecoveryAlreadyPending;
use rule REC_009_ccipSend_RevertWhen_BridgeAmountIsZero;
use rule CFG_004_REC_009_ccipSend_RevertWhen_DestinationChainIsZero;
use rule CFG_004_REC_009_ccipSend_RevertWhen_DestinationIsSelfChain;
use rule CFG_003_REC_009_ccipSend_RevertWhen_DestinationVaultNotRegistered;
use rule CCIP_008_ccipSend_Success;
use rule CCIP_005_REC_002_REC_009_ccipSend_When_RouterGetFeeReverts_StoresRecovery;
use rule CCIP_005_REC_002_REC_009_ccipSend_When_RouterCcipSendReverts_StoresRecovery;
use rule PAUSE_004_executeEpochWithdraw_RevertWhen_Paused;
use rule NONCE_003_NONCE_007_executeEpochWithdraw_RevertWhen_EpochNonceIsNotNew;
use rule executeEpochWithdraw_RevertWhen_CallerDoesNotHaveEPOCH_OPERATOR_ROLE;
use rule REENT_001_executeEpochWithdraw_RevertWhen_ReentrantCall;
use rule NONCE_007_REC_003_executeEpochWithdraw_RevertWhen_RecoveryAlreadyPending;
use rule executeEpochWithdraw_RevertWhen_AmountIsZero;
use rule NONCE_005_executeEpochWithdraw_RevertWhen_NoActiveAdapter;
use rule executeEpochWithdraw_RevertWhen_AmountOutIsZero;
use rule executeEpochWithdraw_RevertWhen_ParentVaultNotRegistered;
use rule NONCE_005_NONCE_006_REC_002_REC_009_executeEpochWithdraw_When_WithdrawFails_StoresRecovery;
use rule CCIP_008_NONCE_003_NONCE_004_executeEpochWithdraw_Success;
use rule CCIP_005_NONCE_005_NONCE_006_REC_002_REC_009_executeEpochWithdraw_When_RouterGetFeeReverts_StoresCcipSendRecovery;
use rule CCIP_005_NONCE_005_NONCE_006_REC_002_REC_009_executeEpochWithdraw_When_RouterCcipSendReverts_StoresCcipSendRecovery;
use rule REENT_001_executeRecovery_REBALANCE_WITHDRAW_RevertWhen_ReentrantCall;
use rule REC_005_REC_009_executeRecovery_REBALANCE_WITHDRAW_RevertWhen_NoActiveAdapter;
use rule REC_005_executeRecovery_REBALANCE_WITHDRAW_RevertWhen_WithdrawFails;
use rule executeRecovery_REBALANCE_WITHDRAW_RevertWhen_AmountRebalancedIsZero;
use rule ADAPTER_002_executeRecovery_REBALANCE_WITHDRAW_Local_RevertWhen_TargetAdapterNotRegistered;
use rule ADAPTER_002_executeRecovery_REBALANCE_WITHDRAW_Local_RevertWhen_TargetAdapterVaultIsInvalid;
use rule REC_001_REC_004_REC_007_REC_008_executeRecovery_REBALANCE_WITHDRAW_Local_Success;
use rule REC_001_REC_002_REC_004_REC_009_executeRecovery_REBALANCE_WITHDRAW_Local_When_DepositFails_StoresRecovery;
use rule executeRecovery_REBALANCE_WITHDRAW_Remote_RevertWhen_TargetChainSelectorIsZero;
use rule executeRecovery_REBALANCE_WITHDRAW_Remote_RevertWhen_TargetVaultNotRegistered;
use rule CCIP_008_REC_001_REC_004_REC_007_REC_008_executeRecovery_REBALANCE_WITHDRAW_Remote_Success;
use rule CCIP_005_REC_001_REC_002_REC_004_REC_009_executeRecovery_REBALANCE_WITHDRAW_Remote_When_RouterGetFeeReverts_StoresCcipSendRecovery;
use rule CCIP_005_REC_001_REC_002_REC_004_REC_009_executeRecovery_REBALANCE_WITHDRAW_Remote_When_RouterCcipSendReverts_StoresCcipSendRecovery;
use rule PAUSE_004_executeRebalance_RevertWhen_Paused;
use rule NONCE_003_NONCE_007_executeRebalance_RevertWhen_RebalanceNonceIsNotNew;
use rule executeRebalance_RevertWhen_CallerDoesNotHaveREBALANCE_OPERATOR_ROLE;
use rule REENT_001_executeRebalance_RevertWhen_ReentrantCall;
use rule NONCE_007_REC_003_executeRebalance_RevertWhen_RecoveryAlreadyPending;
use rule NONCE_005_executeRebalance_RevertWhen_NoActiveAdapter;
use rule executeRebalance_RevertWhen_AmountRebalancedIsZero;
use rule executeRebalance_When_WithdrawFails_RevertWhen_TargetChainSelectorIsZero;
use rule NONCE_005_NONCE_006_REC_002_REC_009_executeRebalance_When_WithdrawFails_StoresRecovery;
use rule ADAPTER_002_executeRebalance_Local_RevertWhen_TargetAdapterNotRegistered;
use rule ADAPTER_002_executeRebalance_Local_RevertWhen_TargetAdapterVaultIsInvalid;
use rule NONCE_003_NONCE_004_executeRebalance_Local_Success;
use rule NONCE_005_NONCE_006_REC_002_REC_009_executeRebalance_Local_When_DepositFails_StoresRecovery;
use rule executeRebalance_Remote_RevertWhen_TargetChainSelectorIsZero;
use rule executeRebalance_Remote_RevertWhen_TargetVaultNotRegistered;
use rule CCIP_008_NONCE_003_NONCE_004_executeRebalance_Remote_Success;
use rule CCIP_005_NONCE_005_NONCE_006_REC_002_REC_009_executeRebalance_Remote_When_RouterGetFeeReverts_StoresCcipSendRecovery;
use rule CCIP_005_NONCE_005_NONCE_006_REC_002_REC_009_executeRebalance_Remote_When_RouterCcipSendReverts_StoresCcipSendRecovery;
use rule REENT_001_executeRecovery_EPOCH_WITHDRAW_RevertWhen_ReentrantCall;
use rule REC_005_REC_009_executeRecovery_EPOCH_WITHDRAW_RevertWhen_NoActiveAdapter;
use rule REC_005_executeRecovery_EPOCH_WITHDRAW_RevertWhen_WithdrawFails;
use rule executeRecovery_EPOCH_WITHDRAW_RevertWhen_AmountOutIsZero;
use rule executeRecovery_EPOCH_WITHDRAW_RevertWhen_ParentChainSelectorInvalid;
use rule executeRecovery_EPOCH_WITHDRAW_RevertWhen_ParentVaultNotRegistered;
use rule CCIP_008_REC_001_REC_004_REC_007_REC_008_executeRecovery_EPOCH_WITHDRAW_Success;
use rule CCIP_005_REC_001_REC_002_REC_004_REC_009_executeRecovery_EPOCH_WITHDRAW_When_RouterGetFeeReverts_StoresCcipSendRecovery;
use rule CCIP_005_REC_001_REC_002_REC_004_REC_009_executeRecovery_EPOCH_WITHDRAW_When_RouterCcipSendReverts_StoresCcipSendRecovery;
use rule CCIP_007_CCIP_008_REC_001_REC_004_REC_007_REC_008_executeRecovery_CCIP_SEND_EPOCH_NET_WITHDRAW_Success;
use rule CCIP_007_CCIP_008_REC_001_REC_004_REC_007_REC_008_executeRecovery_CCIP_SEND_REBALANCE_Success;
use rule CCIP_007_REC_005_executeRecovery_CCIP_SEND_RevertWhen_RouterGetFeeReverts;
use rule CCIP_007_REC_005_executeRecovery_CCIP_SEND_RevertWhen_RouterCcipSendReverts;
use rule REENT_001_executeRecovery_CCIP_SEND_RevertWhen_ReentrantCall;
use rule executeRecovery_CCIP_SEND_RevertWhen_AmountIsZero;
use rule executeRecovery_CCIP_SEND_RevertWhen_DestinationChainSelectorInvalid;
use rule executeRecovery_CCIP_SEND_RevertWhen_DestinationVaultNotRegistered;
use rule CCIP_007_clearCcipSendRecovery_Success;
use rule CCIP_007_REC_005_executeRecovery_CCIP_SEND_RevertWhen_RouterCcipSendCapacityExceeded;
